### ISSUE TITLE
N-ary tree

### ISSUE THREAD

**Issue by Focshole** [michiari/ppl#2]
Good evening,
As suggested in the first lesson, I'll write here a suggestion for an improvement. 
During lesson 2020-10-06-S1.rkt, you have shown us a binary tree. Instead of a binary tree, I wanted to build an n-ary tree as exercise. I had some problem with the #guard construct, and I cannot understand what is it referring to. 
I hope this won't be off-topic, also considering that recent lessons were about Haskell and not Scheme.

Here's the code:
[es1.1.txt](https://github.com/michiari/ppl/files/5512406/es1.1.txt)
I keep not understanding why I keep getting as error:
```
constructor: result arity mismatch;
 expected number of values not received
  expected: 2
  received: 1calling guard procedure
```
Any help would be extremely appreciated, especially cause I cannot understand where does it came from, Google didn't show any relevant result and it seems that the calling guard procedure gets called twice for no reason.

**Comment by michiari** [comment]
Hi, the problem is that the guard lambda should return all arguments of the struct constructor, but the one in your code is returning just `cnodes`.
To implement that guard correctly, you need to make the lambda return multiple values, which we didn't cover in class.
In line 37, just replace `node-var cnodes` with `(values node-var cnodes)`, and it should work.

**Comment by Focshole** [comment]
Thank you very much, it worked!
